### ISSUE TITLE
Vc projects fail to build with clang-7

### ISSUE THREAD

**Issue by kiroma** [VcDevel/Vc#212]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
-|-|-|-|-|-
1.3.3|Kubuntu 18.04|clang-7|-|-|-

## Actual Results
Projects including Vc fail to build at [Vc/sse/intrinsics.h:617](https://github.com/VcDevel/Vc/blob/1.4/Vc/sse/intrinsics.h#L617), with error
```
/home/kiroma/Vc/Vc/scalar/../common/../sse/intrinsics.h:617:13: error: argument to '__builtin_ia32_vec_ext_v4sf' must be a constant integer
            _MM_EXTRACT_FLOAT(f, v, i);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/clang/7.0.0/include/smmintrin.h:890:11: note: expanded from macro '_MM_EXTRACT_FLOAT'
  { (D) = __builtin_ia32_vec_ext_v4sf((__v4sf)(__m128)(X), (int)(N)); }
          ^                                                ~~~~~~~~
```
## Expected Results
Projects successfully compile

**Comment by olupton** [comment]
I was about to report the same thing.

In my case I am using clang 7.0.0 on MacOS ("real" clang, not apple clang). I tried both the 1.4.0 release of Vc and the 1.4 branch in git. Here is the error, for reference.

```
[  5%] Building CXX object CMakeFiles/Vc.dir/trigonometric_SSE4_1.cpp.o
In file included from /Users/olli/build/Vc/build/trigonometric_SSE4_1.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
/Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:617:13: error: argument to '__builtin_ia32_vec_ext_v4sf' must be a constant integer
            _MM_EXTRACT_FLOAT(f, v, i);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-7.0/lib/clang/7.0.0/include/smmintrin.h:890:11: note: expanded from macro '_MM_EXTRACT_FLOAT'
  { (D) = __builtin_ia32_vec_ext_v4sf((__v4sf)(__m128)(X), (int)(N)); }
          ^                                                ~~~~~~~~
1 error generated.
```

With the AppleClang version that comes with XCode it compiles.

**Comment by berolinux** [comment]
Confirmed on Linux with clang 7.0.0.

Another error when building Vc 1.4 with clang 7.0.0:

/usr/bin/clang++   -DVc_IMPL=AVX -I/home/bero/temp/abf/vc/BUILD/Vc-1.4.0  -O2 -g -march=znver1 -mtune=znver1 -std=c++14 -ftemplate-depth=128 -O2 -g -march=znver1 -mtune=znver1   -Wno-local-type-template-args -Wno-unnamed-type-template-args -ffp-contract=fast -DVc_COMPILE_LIB -fPIC -fstack-protector  -mavx -o CMakeFiles/Vc.dir/trigonometric_AVX.cpp.o -c /home/bero/temp/abf/vc/BUILD/Vc-1.4.0/build/trigonometric_AVX.cpp
In file included from /home/bero/temp/abf/vc/BUILD/Vc-1.4.0/build/trigonometric_AVX.cpp:31:
In file included from /home/bero/temp/abf/vc/BUILD/Vc-1.4.0/Vc/vector.h:35:
In file included from /home/bero/temp/abf/vc/BUILD/Vc-1.4.0/Vc/sse/vector.h:401:
In file included from /home/bero/temp/abf/vc/BUILD/Vc-1.4.0/Vc/scalar/../common/../sse/simd_cast.h:33:
/home/bero/temp/abf/vc/BUILD/Vc-1.4.0/Vc/scalar/../common/../sse/../avx/casts.h:80:73: error: argument value -128 is outside the valid
      range [0, 255] [-Wargument-outside-range]
  ...__m256  zeroExtend(__m128  v) { return _mm256_permute2f128_ps   (_mm256_castps128_ps256(v), _mm256_castps128_ps256(v), 0x80); }
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bero/temp/abf/vc/BUILD/Vc-1.4.0/Vc/scalar/../common/../sse/../avx/intrinsics.h:62:11: note: expanded from macro
      '_mm256_permute2f128_ps'
  (__m256)__builtin_ia32_vperm2f128_ps256((__v8sf)(__m256)(V1), \
          ^

**Comment by mattkretz** [comment]
Thanks for your reports. Fixing...

The `permute2f128` errors are due to an earlier clang bug that Vc had to work around: 08ac7ad25ec071e36c67be3da810a133da714ef1.

**Comment by mattkretz** [comment]
Clang 7 is compiling the Vc 1.4 branch for me now. Do any of you need a 1.3 backport? I recommend to move to 1.4 if at all possible. 1.3 has more issues than just this one.

**Comment by kiroma** [comment]
Trying to compile Krita with clang-7 still fails
```
In file included from ../libs/pigment/compositeops/KoOptimizedCompositeOpFactory.cpp:20:
In file included from ../libs/pigment/compositeops/KoOptimizedCompositeOpFactoryPerArch.h:24:
In file included from ../libs/pigment/compositeops/KoVcMultiArchBuildSupport.h:39:
In file included from /usr/local/include/Vc/Vc:39:
In file included from /usr/local/include/Vc/span:1:
/usr/local/include/Vc/common/span.h:316:23: error: constexpr function's return type 'void' is not a literal type
    Vc_CONSTEXPR void swap(span& _other) noexcept
                      ^
/usr/local/include/Vc/common/span.h:509:23: error: constexpr function's return type 'void' is not a literal type
    Vc_CONSTEXPR void swap(span& _other) noexcept
                      ^
/usr/local/include/Vc/common/span.h:589:19: error: constexpr function's return type 'void' is not a literal type
Vc_CONSTEXPR void swap(span<T, Extent>& lhs, span<T, Extent>& rhs) noexcept
                  ^
3 errors generated.
```

**Comment by olupton** [comment]
I tested the fix on MacOS/clang-7 and it compiled cleanly. Thanks!

**Comment by mattkretz** [comment]
> Trying to compile Krita with clang-7 still fails

Is this building with `-std=c++11`? The code is certainly valid C++17, but it may be ill-formed C++11, I don't recall for certain.

**Comment by mattkretz** [comment]
I was able to reproduce the problem with `-std=c++11`. The constexpr usage in `Vc::span` requires C++14. Fix is pushed.

**Comment by oshadura** [comment]
Hi Matthias! :)
We upgraded ROOT to use Vc tag 1.4.0, but apparently this tag still doesn't include fixes for Clang7/8.
```
[  1%] Building CXX object CMakeFiles/Vc.dir/trigonometric_SSE4_1.cpp.o
In file included from /home/oksana/CERN_sources/Vc/builds/trigonometric_SSE4_1.cpp:31:
In file included from /home/oksana/CERN_sources/Vc/Vc/vector.h:35:
In file included from /home/oksana/CERN_sources/Vc/Vc/sse/vector.h:32:
/home/oksana/CERN_sources/Vc/Vc/scalar/../common/../sse/intrinsics.h:617:13: error: argument to '__builtin_ia32_vec_ext_v4sf' must be a constant integer
            _MM_EXTRACT_FLOAT(f, v, i);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/contrib/llvm/builds/x86_64-centos7-gcc62-opt/clang_build_346891/lib/clang/8.0.0/include/smmintrin.h:890:11: note: expanded from macro '_MM_EXTRACT_FLOAT'
  { (D) = __builtin_ia32_vec_ext_v4sf((__v4sf)(__m128)(X), (int)(N)); }
          ^                                                ~~~~~~~~
1 error generated.
```
Can I ask you please if you can make a new tag?

Thank you so much in advance!

**Comment by mattkretz** [comment]
@oshadura will do ASAP

**Comment by mattkretz** [comment]
1.4.1 is out now

**Comment by oshadura** [comment]
@mattkretz Thank you so much!
